-- MandoMemori: пользователи
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(100) NOT NULL UNIQUE,
    mail VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    firstname VARCHAR(100) NOT NULL DEFAULT '',
    lastname VARCHAR(100) NOT NULL DEFAULT '',
    avatar VARCHAR(255) DEFAULT NULL,
    points INTEGER NOT NULL DEFAULT 0,
    adress VARCHAR(255) DEFAULT '',
    city VARCHAR(100) DEFAULT '',
    phone VARCHAR(30) DEFAULT '',
    descriptions TEXT DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
